language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

install:
  - export PIP_USE_MIRRORS=true
  - pip install --upgrade pytest  # https://github.com/travis-ci/travis-ci/issues/4873
  - pip install --upgrade pip wheel virtualenv setuptools
  - pip install -r requirements/test.txt
  - pip install DJANGO==$DJANGO_VERSION

script: coverage run --source django_docutils runtests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
