language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

install:
  - pip install -r requirements/test.txt
  - pip install DJANGO==$DJANGO_VERSION

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source django_docutils runtests.py

# report coverage to coveralls.io
after_success: coveralls
