language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

install:
  - pip install -r requirements/test.txt
  - pip install DJANGO==$DJANGO_VERSION

script: coverage run --source django_docutils runtests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
