[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "django-docutils"
version = "0.4.0"
description = "Documentation Utilities (Docutils, reStructuredText) for django.)"

license = "MIT"

authors = [
    "Tony Narlock <tony@git-pull.com>"
]

readme = 'README.rst'  # Markdown files are supported

repository = "https://github.com/tony/django-docutils"
homepage = "https://django-docutils.git-pull.com"
documentation = "https://django-docutils.git-pull.com"

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/tony/django-docutils/issues"

[tool.poetry.dependencies]
python = "^3.6"
Django = ">=2.2"
docutils = ">=0.12"
tldextract = {version = "^2.2.2", optional = true}
tqdm = {version = "^4.41.0", optional = true}
pygments = {version = "^2.5.2", optional = true}

[tool.poetry.extras]
favicon = ["tldextract", "tqdm"]
intersphinx = ["tqdm"]


[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
isort = "^4.3.21"
black = "^19.10b0"
sphinx = ">=2.0.0"
alagitpull = "<1"
sphinx_issues = "<2"
pytest = "<6"
coverage = "^5.0.1"
pytest-cov = "^2.8.1"
factory-boy = "^2.12.0"
pytest-factoryboy = "^2.0.3"
dj-inmemorystorage = "^2.0.0"
responses = "^0.10.9"

[tool.black]
skip-string-normalization = true
include = '\.pyi?$'
