[tool.poetry]
name = "django-docutils"
version = "0.4.0"
description = "Documentation Utilities (Docutils, reStructuredText) for django.)"

license = "MIT"

authors = [
    "Tony Narlock <tony@git-pull.com>"
]

readme = 'README.rst'  # Markdown files are supported

repository = "https://github.com/tony/django-docutils"
homepage = "https://django-docutils.git-pull.com"
documentation = "https://django-docutils.git-pull.com"

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/tony/django-docutils/issues"

[tool.poetry.dependencies]
python = ">3.6"
Django = ">=2.2"
docutils = ">=0.12"
tldextract = {version = "^2.2.2", optional = true}
tqdm = {version = "^4.41.0", optional = true}
pygments = {version = "^2.5.2", optional = true}

[tool.poetry.extras]
favicon = ["tldextract", "tqdm"]
intersphinx = ["tqdm"]

[tool.black]
skip-string-normalization = true
include = '\.pyi?$'
